services:
#    base.example:
#        class: BaseBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  redirect.after.login:
    class: LocalBundle\Redirection\AfterLoginRedirection
    arguments: ['@router']